language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry composer require codeclimate/php-test-reporter --dev

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
